project/city/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.book),
    path('detail/list/', views.book),
    # 传递参数url
    path('need/<cate:book_id>/<cate:book_id2>/', views.need),
    # re_path("?P<book_id>")
    # /? Get 请求访问id=1
    path('need/conference/', views.conference),
    path('look/', views.books),
    path('look/<int:page>/', views.books),
    path('douban/', views.douban),
    path('read/', views.read, name='read'),
    path('movie/<dog>', views.movie, name='movie'),
    path('city/', views.city, name='city'),
    path('autospace/', views.auto_space, name='autospace'),
    path('include/', views.include)
]
# + static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS[0])


project/cms/urls.py
from django.urls import path, re_path
from . import views

# 应用命名空间
# 应用命名空间的变量叫做app_name
app_name = 'cms'

urlpatterns = [
    path('', views.index),
    path('sing/', views.login, name='login'),
    re_path(r"reverse/(?P<nian>[0-9]{4})/(?P<yue>[0-9]{2})", views.reverse2,
            name='reverse'),
    path('reverse/', views.reverse1, name='re'),
    # re_path(r"^PD$", views.reverse)
]

project/front/urls.py
from django.urls import path
from . import views


app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.login, name='login')
]


project/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('book/', include(('city.urls', 'city'), namespace='book')),
    # path('book/detail/', city.detail)
    path('', include('front.urls')),
    path('cms1/', include('cms.urls', namespace='cms1')),
    path('cms2/', include('cms.urls', namespace='cms2'))
    # path('cms', include(('city.urls', 'book'), namespace='1'))
    # path('cms', include（[path()],('city.urls', 'book', namespace='2')）
]

project/city/models.py
from django.db import models

# Create your models here.

project/cms/models.py
from django.db import models

# Create your models here.

project/front/models.py
from django.db import models

# Create your models here.

project/city/views.py
from django.http import HttpResponse
# from django.template.loader import render_to_string
from django.shortcuts import render
from datetime import datetime
from django.db import connection


class Game():
    def __init__(self, name):
        self.name = name


book_list = [
    "水浒传",
    "西游记",
    "红楼梦",
    "三国演义"
]


def book(request):
    p = Game('lol')
    context = {
        'username': {
            'zhiliao': 'dengping'
        },
        'game': p,
        'age': 18,
        'books': [
            '红楼梦',
            '西游记',
            '水浒传',
            '三国演义'
        ],
        'person': {
            'username': 'dengping',
            'age': 18,
            'height': 180
        },
        'booklove': [
            {
                '书名': '三国演义',
                '作者': '罗贯中',
                '价格': 20
            },
            {
                '书名': '水浒传',
                '作者': '施耐庵',
                '价格': 25
            },
            {
                '书名': '红楼梦',
                '作者': '曹雪芹',
                '价格': 99
            },
            {
                '书名': '西游记',
                '作者': '罗贯中',
                '价格': 89
            }
        ]
    }
    # list = render_to_string('book.html')
    return render(request, 'book.html', context=context)


def books(request, page=0):
    return HttpResponse(book_list[page])


def need(request, book_id, book_id2):
    text = "您获取的图书：%s%s" % (book_id, book_id2)
    return HttpResponse(text)


def conference(request):
    """视图函数传递url键值对"""
    conference_id = request.GET.get('id')
    text = 'conference:%s' % conference_id
    return HttpResponse(text)


def douban(request):
    return render(request, 'url.html')


def read(request):
    read = request.GET.get('name')
    return HttpResponse(read)


def movie(request, dog):
    return HttpResponse('电影首页')


def city(request):
    return render(request, 'include.html')


def auto_space(request):
    cursor = connection.cursor()
    # cursor.execute("insert into book(id,name,author) values(null,'三国演义','罗贯中')")
    cursor.execute("select id,name,author from book")
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    context = {
        'info': "<a href='www.baidu.com'>百度</a>",
        'birthday': datetime.now(),
        'file': 'name:',
        'datatime': datetime(year=2018, month=11, day=19,
                             hour=21, minute=8, second=0)
    }
    return render(request, 'autoescape.html', context=context)


def include(request):
    return render(request, 'include.html')

project/cms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect, reverse

# Create your views here.


def index(request):
    username = request.GET.get('username')
    if username:
        return HttpResponse('CMS首页')
    else:
        current_namespace = request.resolver_match.namespace  # 获取当前实例命名空间
        return redirect(reverse("%s:login" % current_namespace))


def reverse1(request):
    re = request.GET.get('name')
    if re:
        return HttpResponse('登陆页面：%s' % re)
    else:
        reverse1_namespace = request.resolver_match.namespace
        print(reverse1_namespace)
        bug = reverse('%s:reverse' % reverse1_namespace, kwargs={"nian": 2014, "yue": 12})
        print(bug)
        return redirect(bug)


def login(request):
        return HttpResponse('CMS登陆页面')


def reverse2(request, nian, yue):
    return HttpResponse('reverse')

project/front/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect, reverse
# Create your views here.


def index(request):
    """如果没有登陆用户名，跳转登陆页面"""
    username = request.GET.get('username')
    if username:
        return HttpResponse('前台首页')
    else:
        # reverse('login'） == /signin
        # return redirect('/signin/')
        # 先重定向（redirect（））再反转（reverse（））
        return redirect(reverse('front:login'))


def login(request):
    return HttpResponse('前台登陆页面')

project/templates/autoescape.html
{% load my_filter %}
{% load filter_time %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="{% static 'dengping.jpg' %}" alt="">
<ul>
    {{ datatime|time_since }}
    {{ file|ge:"dengping" }}
    {{ info|safe }}
    {% autoescape off %}
        {{ info }}
    {% endautoescape %}
    {% verbatim %}
    {{ info }}
    {% endverbatim %}

    {{ "1"|add:"2" }}

    {{ birthday|date:"d-m-Y" }}

    {{ "hallo world"|cut:"w" }}
    {{ info|default:"is nothing" }}
</ul>

</body>
</html>

project/templates/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>这是一个渲染的模版</title>
</head>
<body>
<img src="/static/dengping.jpg" alt="">
    这是一个渲染的模版
    {{ username.zhiliao }}
    {{ game.name }}
    {% if age < 18 %}
        <p>您是未成年人，不可以进入网吧</p>
    {% elif age == 18 %}
        <p>您满18岁，可以进入网吧</p>
    {% else %}
        <p>您已经是成年人了，需要承担起家庭责任，不可以进入而网吧</p>
    {% endif %}

    <ul>
        {% for book in books reversed %}
            <li>{{ book }}</li>
        {% endfor %}

    </ul>
    <p>
        {% for key,value in person.items %}
            <li>{{ key }}/{{ value }}</li>
        {% endfor %}

    </p>
    <table>
        <thead>
            <tr>
                <td>序号</td>
                <td>书名</td>
                <td>作者</td>
                <td>价格</td>
            </tr>
        </thead>
        <tbody>
            {% with  booklove as bookloves %}
            {% for book in bookloves %}
                {% if forloop.first %}
                    <tr style="background: aqua;">
                {% elif forloop.last %}
                    <tr style="background: aquamarine;">
                {% else %}
                    <tr>
                {% endif %}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ book.书名 }}</td>
                    <td>{{ book.作者 }}</td>
                    <td>{{ book.价格 }}</td>
            {% endfor %}
            {% endwith %}
        </tbody>
    </table>
</body>
</html>

project/templates/include.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <header>
        {% include "include_header.html" with username="zhiliao" %}
    </header>
    <div class="content">
        这是中间内容
    </div>
    <footer>
        这是footer部分
    </footer>
</body>
</html>

project/templates/include_header.html
<ul>

    <li><a href="{% url 'book:city' %}">首页</a></li>
    <li><a href="#">公司</a></li>
    <li><a href="#">校园</a></li>
    <li>{{ username }}</li>

</ul>

project/templates/load_father.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block title %}
    {{ block.super }}
    {% endblock %}

</body>
</html>

project/templates/load_son.html
{% extends 'load_father.html' %}
{% load static %}

{% block title%}
    <img src="{% static 'cms/logo.jpg' %}" alt="">
{% endblock %}

project/templates/url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>urllabel</title>
    <style>
        .nav{
            overflow: hidden;
        }
        .nav li{
            float: left;
            list-style: none;
            margin: 0 20px;
        }
    </style>
</head>
<body>
    <ul class="nav">
        <li><a href="/book">首页</a></li>
        <li><a href="{% url 'book:read' %}?name=/">读书</a></li>
        <li><a href="{% url 'book:movie' dog=1 %}">电影</a></li>
        <li><a href="{% url 'book:city' %}?name=/">同城</a></li>
    </ul>
</body>
</html>