logistics/apps/school/urls.py
from django.urls import path
from apps.school import views

app_name = 'school'

urlpatterns = [
    path('', views.EnterScore.as_view(), name='enter_score'),
    path('score/', views.ShowList.as_view(), name='show_score'),
    path('openpyxl/', views.excel_write, name='openpyxl'),
    path('download/', views.download, name='download')
]

logistics/logistics/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from apps.index import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index'),
    path('index/', include('apps.index.urls')),
    path('logistics/', include('apps.logistics_auth.urls', namespace='logistics1')),
    #  namespace：实例命名空间
    path('bank/', include('apps.bank.urls')),
    path('school/', include('apps.school.urls')),
]

logistics/front/templates/shcool/entersocre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>成绩录入</title>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script>
        $(function () {
            $("#submit").click(function (event) {
                event.preventDefault();
                var telephone = $("input[name='telephone']").val();
                var username = $("input[name='username']").val();
                var email = $("input[name='email']").val();
                var password = $("input[name='password']").val();
                var password_repeat = $("input[name='password_repeat']").val();

                myajax.post({
                    'url': '/school/',
                    'data': {
                    },
                    'success': function (data) {
                        console.log(data);
                    },
                    'fail': function (error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
</head>
<body>
<form action="#" method="post">
    {% csrf_token %}
    <table>
        <tbody>
        <tr>
            <td><input type="submit" id="submit"></td>
        </tr>
        </tbody>
    </table>
</form>
</body>
</html>

logistics/front/templates/shcool/showlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
</head>
<body>
<ul>
    {% for score in scores %}
        <li>{{ score }}</li>
    {% endfor %}
    <ul class="pagination">
        {#上一页#}
        {% if has_previous %}
            <li>
                <a href="{% url 'school:show_score' %}?page={{ previous_page_number }}">上一页</a>
            </li>
        {% else %}
            <li class="disabled"><a href="javascript:void(0)">上一页</a></li>
        {% endif %}
        {#中间部分#}
        {# 左边页码 #}
        {% if left_has_more %}
            <li>
                <a href="{% url 'school:show_score' %}?page=1">1</a>
            </li>
            <li>
                <a href=#>...</a>
            </li>
            {% for left_page in left_pages %}
                <li>
                    <a href="{% url 'school:show_score' %}?page={{ left_page }}">{{ left_page }}</a>
                </li>
            {% endfor %}
        {% else %}
            {% for left_page in left_pages %}
                <li>
                    <a href="{% url 'school:show_score' %}?page={{ left_page }}">{{ left_page }}</a>
                </li>
            {% endfor %}

        {% endif %}

        {# 中间页码 #}
        <li class="active">
            <a href="{% url 'school:show_score' %}?page={{ current_page }}">{{ current_page }}</a>
        </li>
        {# 右边页码 #}
        {% if right_has_more %}
            {% for right_page in right_pages %}
                <li>
                <a href="{% url 'school:show_score' %}?page={{ right_page }}">{{ right_page }}</a>
                </li>
            {% endfor %}
            <li><a href="javascript:void(0)">...</a></li>
            <li><a href="{% url 'school:show_score' %}?page={{ page_sum }}">{{ page_sum }}</a></li>
        {% else %}
            {% for right_page in right_pages %}
                <li>
                    <a href="{% url 'school:show_score' %}?page={{ right_page }}">{{ right_page }}</a>
                </li>
            {% endfor %}
        {% endif %}
        {#下一页#}
        {% if has_next %}
            <li>
                <a href="{% url 'school:show_score' %}?page={{ next_page_number }}">下一页</a>
            </li>
        {% else %}
            <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
        {% endif %}
    </ul>
</ul>
</body>
</html>