logistics/apps/index/urls.py
from django.urls import path
from apps.index import views

app_name = 'index'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register')
    # path('transfer/', views.TransferView.as_view(), name='transfer'),
]

logistics/apps/logistics_auth/urls.py
from django.urls import path
from apps.logistics_auth import views

app_name = 'logistics_auth'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

logistics/logistics/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from apps.index import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index'),
    path('index/', include('apps.index.urls')),
    path('logistics/', include('apps.logistics_auth.urls', namespace='logistics1')),
    #  namespace：实例命名空间
    path('bank/', include('apps.bank.urls')),
    path('school/', include('apps.school.urls')),
]

logistics/front/templates/index/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>爱无止境</title>
</head>
<body>
{% csrf_token %}
<div class="auth-box">
    <i class="icon-person iconfont"></i>
    {% if user.is_authenticated %}
        <a href="#" class="authenticated-box">{{ user.username }}</a>
        {#   使用上下文处理器的user对象获取username字段   #}
        <div class="user-more-box">
            <i class="triangle"></i>
            <a href="#">管理系统</a>
            <a href="{% url 'logistics1:logout' %}">退出登录</a>
        </div>
    {% else %}
        <a href="{% url 'index:login' %}" class="signin-btn">登录</a> /
        <a href="{% url 'index:register' %}" class="signup-btn">注册</a>
    {% endif %}
</div>

<div class="mask-wrapper">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <span class="close-btn icon-close iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   name="telephone" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control"
                                   name="password" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remember-label">
                                <input type="checkbox" name="remember"
                                       value="1">
                                下次自动登录
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn"
                                   value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript: void(0);" class="switch">立即登录></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   name="telephone" placeholder="手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   name="username" placeholder="用户名">
                        </div>
                        <div class="input-group">
                            <input type="email" class="form-control"
                                    name="email" placeholder="邮箱">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   name="password1" placeholder="密码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control"
                                   name="password2" placeholder="确认密码">
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn"
                                   value="立即注册">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

logistics/front/templates/index/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到登陆界面</title>
    <link rel="stylesheet" href="{% static 'css/common/login.css' %}">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script>
        $(function () {
            $("#submit").click(function (event) {
                event.preventDefault();
                var telephone = $("input[name='telephone']").val();
                var password = $("input[name='password']").val();
                var remember = $("input[name='remember']").prop("checked");

                myajax.post({
                    'url': '/logistics/login/',
                    'data': {
                        'telephone': telephone,
                        'password': password,
                        'remember': remember?1:0,
                    },
                    'success': function (data) {
                        console.log(data);
                    },
                    'fail': function (error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
</head>
<body>
    <table>
        <tbody>
            <tr>
                <td>电话:</td>
                <td><input type="text" name="telephone"></td>
            </tr>
            <tr>
                <td>密码：</td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <td>下次自动登录:</td>
                <td><input type="checkbox" name="remember" value="1"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" id="submit"></td>
            </tr>
        </tbody>
    </table>
</body>
</html>

logistics/front/templates/index/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到注册界面</title>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script>
        $(function () {
            $("#submit").click(function (event) {
                event.preventDefault();
                var telephone = $("input[name='telephone']").val();
                var username = $("input[name='username']").val();
                var email = $("input[name='email']").val();
                var password = $("input[name='password']").val();
                var password_repeat = $("input[name='password_repeat']").val();

                myajax.post({
                    'url': '/logistics/register/',
                    'data': {
                        'telephone': telephone,
                        'username': username,
                        'email': email,
                        'password': password,
                        'password_repeat': password_repeat
                    },
                    'success': function (data) {
                        console.log(data);
                    },
                    'fail': function (error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
</head>
<body>
<form action="#" method="post">
    {% csrf_token %}
    <table>
        <tbody>
        <tr>
            <td>电话:</td>
            <td><input type="text" name="telephone"></td>
        </tr>
        <tr>
            <td>用户名：</td>
            <td><input type="text" name="username"></td>
        </tr>
        <tr>
            <td>邮箱：</td>
            <td><input type="email" name="email"></td>
        </tr>
        <tr>
            <td>密码：</td>
            <td><input type="password" name="password"></td>
        </tr>
        <tr>
            <td>确认密码:</td>
            <td><input type="password" name="password_repeat"></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" id="submit"></td>
        </tr>
        </tbody>
    </table>
</form>
</body>
</html>